<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="68162" started-at="2019-10-16T09:45:54Z" finished-at="2019-10-16T09:47:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="68162" started-at="2019-10-16T09:45:54Z" finished-at="2019-10-16T09:47:02Z">
      <class name="testCases.Customer">
        <test-method status="PASS" signature="Setup()[pri:0, instance:testCases.Customer@1da2cb77]" name="Setup" is-config="true" duration-ms="34421" started-at="2019-10-16T15:15:54Z" finished-at="2019-10-16T15:16:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="VerifyCustomerData()[pri:0, instance:testCases.Customer@1da2cb77]" name="VerifyCustomerData" duration-ms="33613" started-at="2019-10-16T15:16:28Z" finished-at="2019-10-16T15:17:02Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerExceptionat java.io.File.<init>(File.java:277)at com.viome.components.ExcelToJSONConvertor.SetFailureStatus(ExcelToJSONConvertor.java:259)at testCases.Customer.VerifyCustomerData(Customer.java:123)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyCustomerData -->
        <test-method status="PASS" signature="Teardown()[pri:0, instance:testCases.Customer@1da2cb77]" name="Teardown" is-config="true" duration-ms="9" started-at="2019-10-16T15:17:02Z" finished-at="2019-10-16T15:17:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- testCases.Customer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
